version: 2.1

# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ Executors ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ #
orbs:
  cypress: cypress-io/cypress@2

# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ Commands ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ #

# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ Workflows ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ #
workflows:
  linux:
    jobs:
      - cypress/install:
          executor: cypress/browsers:node16.14.2-slim-chrome100-ff99-edge

      - cypress/run:
          name: Chrome
          executor: cypress/browsers:node16.14.2-slim-chrome100-ff99-edge
          requires:
            - cypress/install
          browser: chrome
          group: chrome
          parallel: true
          parallelism: 2
          record: true
          command: npm run test:ci:chrome
          post-steps:
            - store_artifacts:
                path: coverage
          no-workspace: true

      - cypress/run:
          name: Firefox
          executor: cypress/browsers:node16.14.2-slim-chrome100-ff99-edge
          requires:
            - cypress/install
          browser: firefox
          group: firefox
          parallel: true
          parallelism: 2
          record: true
          command: npm run test:ci:firefox
          post-steps:
            - store_artifacts:
                path: coverage
          no-workspace: true

      - cypress/run:
          name: Edge
          executor: cypress/browsers:node16.14.2-slim-chrome100-ff99-edge
          requires:
            - cypress/install
          browser: edge
          group: edge
          parallel: true
          parallelism: 2
          record: true
          command: npm run test:ci:edge
          post-steps:
            - store_artifacts:
                path: coverage
          no-workspace: true
